### ISSUE TITLE
Project Performance Review

### ISSUE THREAD

**Issue by zackha** [vernaillen/wpnuxt-demo#29]
Hello @vernaillen,

I’ve reviewed the demo of your project, but it’s running very slowly. Could this be due to the server where WordPress is installed?

Best,

**Comment by vernaillen** [comment]
Hi @zackha,

Are you running the code locally or do you mean the online demo at https://demo.wpnuxt.com/?   

The latter seems fine to me: https://page-speed.dev/demo.wpnuxt.com

**Comment by zackha** [comment]
I'm referring to the demo at https://demo.wpnuxt.com/.

**Comment by vernaillen** [comment]
I'm just wondering if this version, deployed at Vercel, is faster for you?  https://wpnuxt-demo.vercel.app/

https://demo.wpnuxt.com is hosted with Coolify on a server at Hetzner in Germany. For me it is quite fast, i'm in Belgium. But I'm not sure if it's loading as fast from other countries.

The content is cached in the Nuxt app. It's not fetched from WordPress on every page request, so I don't think the performance issue will be on the WordPress side.

**Comment by zackha** [comment]
Yes, this one opens a bit faster. I think data is being fetched from the API at the beginning.

**Comment by vernaillen** [comment]
@zackha it turns out there was an issue with the wordpress instance after all. I'm not sure what's causing it. But the demo is now connecting to another wordpress instance deployed at WPEngine.

I also tweaked the route prerendering. The demo should be a lot faster now.

Thanks a lot for your feedback on this!

**Comment by zackha** [comment]
> @zackha it turns out there was an issue with the wordpress instance after all. I'm not sure what's causing it. But the demo is now connecting to another wordpress instance deployed at WPEngine.
> 
> I also tweaked the route prerendering. The demo should be a lot faster now.
> 
> Thanks a lot for your feedback on this!

Thank you, best regards.
